/** Declaration file generated by dts-gen */

interface HomebridgeUser {
    storagePath(): string;
}

export class API {
    user: HomebridgeUser

    constructor();

    accessory(name: any): any;

    platform(name: any): any;

    publishCameraAccessories(pluginName: any, accessories: any): void;

    publishExternalAccessories(pluginName: any, accessories: any): void;

    registerAccessory(pluginName: any, accessoryName: any, constructor: any, configurationRequestHandler: any): void;

    registerPlatform(pluginName: any, platformName: any, constructor: any, dynamic: any): void;

    registerPlatformAccessories(pluginName: any, platformName: any, accessories: any): void;

    unregisterPlatformAccessories(pluginName: any, platformName: any, accessories: any): void;

    updatePlatformAccessories(accessories: any): void;

}